### ISSUE TITLE
Broken UIDs?

### ISSUE THREAD

**Issue by CMcStone** [CMcStone/dssweb.buildout#1]
The links at the bottom of this page are broken (UID links):  http://dss-web1-2060342375.us-west-2.elb.amazonaws.com/iss/opportunities/Lead%20a%20Proseminar/iss-proseminar.  I'm not sure it's a concern, since we can fix it post migration.

**Comment by cguardia** [comment]
I will keep an eye on this during migration.

**Comment by CMcStone** [comment]
fixed after migration
